apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  namespace: grc-e2e-policy-generator
  labels:
    app: gitops-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitops-demo
