apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: e2e-grc-policy-generator
placementBindingDefaults:
  name: e2e-grc-placement-binding
policyDefaults:
  controls:
    - PR.DS-1 Data-at-rest
  description: "~This is a policy_generator test description!@#"
  policyLabels:
    e2e: "true"
    testid: "100"
  namespace: default
  placement:
    name: e2e-grc-placement-rule-42156
    clusterSelectors:
      local-cluster: "true"
  remediationAction: enforce
  severity: medium
policies:
  - name: rhacm4k-42156
    manifests:
      - path: policy1
